services:
  api:
    image: rahullore/product-orders:app-latest
    container_name: customer-orders-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - API_KEY=${API_KEY}
      - BASE_URL=${BASE_URL}
      - MODEL=${MODEL}
      #open ai settings
      - EMBEDDED_API_KEY=${EMBEDDED_API_KEY}
      - EMBEDDED_BASE_URL=${EMBEDDED_BASE_URL}
      - EMBEDDED_MODEL=${EMBEDDED_MODEL}
      #sql server settings
      - ConnectionStrings__Sql=Server=sqlserver,1433;Database=ProductOrders;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;

    ports:
      - "5178:8080"  # host port -> container port
    networks:
      - appnet

  web:
    image: rahullore/product-orders:web-latest
    container_name: customer-orders-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # important for docker/runtime (not secret)
      - NUXT_PUBLIC_API_BASE=/demo1
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - appnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: product-orders-sql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Your_password123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

networks:
  appnet:
volumes:
  sql_data:
